FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app  
EXPOSE 443  
EXPOSE 80  

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src  
COPY ["Backend.csproj", ""]  
RUN dotnet restore "./Backend.csproj"  
COPY . . 
RUN dotnet build "Backend.csproj" -c Release -o /app/build  

FROM build AS publish  
RUN dotnet publish "Backend.csproj" -c Release -o /app/publish  

FROM base AS final  
LABEL org.opencontainers.image.source https://github.com/Vergiet/hss
WORKDIR /app  
COPY --from=publish /app/publish .  
ENTRYPOINT ["dotnet", "Backend.dll"] 