FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY "ForecastGenerator.csproj" .
RUN dotnet restore "ForecastGenerator.csproj"
COPY . .
RUN dotnet build "ForecastGenerator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ForecastGenerator.csproj" -c Release -o /app/publish

FROM base AS final
LABEL org.opencontainers.image.source https://github.com/Vergiet/hss
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ForecastGenerator.dll"]