apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: ui-{{ default "staging" .Release.Namespace }}.{{ .Values.dns.name }}
      http:
        paths:
          - backend:
              serviceName: ui
              servicePort: 80
            path: /