apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  ports:
  - port: 80
  selector:
    app: ui
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: backend
