FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY Ui.csproj .
RUN dotnet restore "Ui.csproj"
COPY . .
RUN dotnet build "Ui.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ui.csproj" -c Release -o /app/publish

FROM base AS final
LABEL org.opencontainers.image.source https://github.com/Vergiet/hss
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Ui.dll"]