name: build ui
env:
  version: "0.1.6"

on:
  push:
    branches: ["hello-world"]
    paths:
      - "ui/**"
      - ".github/workflows/build.ui.yml"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        apps: ["ui"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github CR
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_WRITETOKEN }}
          registry: ghcr.io
      - name: Build and push ${{ matrix.apps }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.apps }}/.
          file: ./${{ matrix.apps }}/dockerfile
          push: true
          tags: ghcr.io/vergiet/${{ matrix.apps }}:latest, ghcr.io/vergiet/${{ matrix.apps }}:${{env.version}}
