name: deploy


on:
  registry_package:
    types: [published, updated]
  workflow_run:
    workflows: ["build"]
    types: 
      - completed

jobs:  
  Deploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: 'aks-temp'
        resource-group: 'aks-temp'
    - name: deploy container to aks
      uses: Azure/k8s-deploy@v1.3
      with:
        manifests: |
            ./kubernetes/deploy.yml
        images: ghcr.io/vergiet/backend:latest
        kubectl-version: 'latest'