name: Infra Destroy

on:
  workflow_dispatch:

jobs:
  stop-running-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_2 }}
          enable-AzPSSession: true

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            if (Get-AzStreamAnalyticsJob -ResourceGroupName aks-temp | ?{$_.JobName -eq "example-job" -and $_.jobstate -ne 'Created' -and $_.jobstate -ne 'Stopped'} | Tee-Object -Variable azStreamAnaJob){
              $azStreamAnaJob | %{ Stop-AzStreamAnalyticsJob -name $_.jobname -ResourceGroupName $_.ResourceGroupName }
            }
          azPSVersion: "latest"

  aks-config-destroy:
    runs-on: ubuntu-latest
    needs: stop-running-jobs

    env:
      ARM_CLIENT_ID: 4d133757-c6ec-4421-a92a-c9051aeaf2ec
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET_2}}
      ARM_SUBSCRIPTION_ID: f3f5415e-60df-46be-bedb-c5465568b158
      ARM_TENANT_ID: 6800fb13-bbf4-4885-a72e-a936ce5796da
      tf_working_dir: ./.kubernetes/aks-config

    defaults:
      run:
        working-directory: ${{ env.tf_working_dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_2 }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --resource-group aks-temp --name aks-temp --context aks-temp -f $GITHUB_WORKSPACE/.kubernetes/.kube/config --overwrite-existing

      - run: sudo chmod +r $GITHUB_WORKSPACE/.kubernetes/.kube/config

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform destroy -auto-approve -var="context_config=$GITHUB_WORKSPACE/.kubernetes/.kube/config" -var="namespace=production"

  infra-destroy:
    runs-on: ubuntu-latest
    needs: aks-config-destroy

    env:
      ARM_CLIENT_ID: 4d133757-c6ec-4421-a92a-c9051aeaf2ec
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET_2}}
      ARM_SUBSCRIPTION_ID: f3f5415e-60df-46be-bedb-c5465568b158
      ARM_TENANT_ID: 6800fb13-bbf4-4885-a72e-a936ce5796da
      tf_working_dir: ./.kubernetes/infra

    defaults:
      run:
        working-directory: ${{ env.tf_working_dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform destroy -auto-approve -var="github_token=${{secrets.GHCR_WRITETOKEN}}"
