name: Terraform Aks Config Plan

on:
  workflow_run:
    workflows: ["Terraform Infra Apply"]
    types:
      - completed

jobs:
  terraform-aks-config:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 03a04d55-d299-4aad-97f6-176d371d9c1a
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: 233516f9-0a43-4284-8ffc-a401b6223e82
      ARM_TENANT_ID: 6800fb13-bbf4-4885-a72e-a936ce5796da
      tf_working_dir: ./.kubernetes/aks-config

    defaults:
      run:
        working-directory: ${{ env.tf_working_dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: ls -la .

      - run: pwd

      - run: ls -la /

      - run: 'ls -la "$GITHUB_WORKSPACE" '

      - run: 'ls -la "$HOME" '

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --resource-group aks-temp --name aks-temp --context aks-temp -f $GITHUB_WORKSPACE/.kubernetes/.kube/config --overwrite-existing

      - run: "whoami"

      - run: 'ls -la "$GITHUB_WORKSPACE/.kubernetes" '

      - run: 'ls -la "$GITHUB_WORKSPACE/.kubernetes/.kube" '

      - run: sudo chmod +r $GITHUB_WORKSPACE/.kubernetes/.kube/config

      - run: cat $GITHUB_WORKSPACE/.kubernetes/.kube/config

      - run: kubectl config view --kubeconfig=$GITHUB_WORKSPACE/.kubernetes/.kube/config

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -var="context_config=$GITHUB_WORKSPACE/.kubernetes/.kube/config"
